### ISSUE TITLE
qr code not generated

### ISSUE THREAD

**Issue by unfairDude** [S0GDevs/Fake-Verification-QR-Discord-S0G-Edition#2]

**Comment by S0GDevs** [comment]
QR code note displayed, will verify API

**Comment by unfairDude** [comment]
thank you

**Comment by S0GDevs** [comment]
QR Code generation is being blocked by remote QR Code provider (they changed of policy and now block use of "https://" data).
Will find an alternative and commit

**Comment by S0GDevs** [comment]
Bypassed restrictions. Will commit asap.

**Comment by S0GDevs** [comment]
A fix has been commited. Enjoy !
