### ISSUE TITLE
keyerror: encrypted token

### ISSUE THREAD

**Issue by unfairDude** [S0GDevs/Fake-Verification-QR-Discord-S0G-Edition#4]

**Comment by unfairDude** [comment]
get this error after scanning qr code

**Comment by S0GDevs** [comment]
Is it with every discord account ?

**Comment by unfairDude** [comment]
Yes every discord account

**Comment by S0GDevs** [comment]
Possibly related to role giving.
Either that or the response data is not formatted correctly.
Will investigate Wednesday night/Thursday

**Comment by unfairDude** [comment]
I don't think it's related to roles, my config value is set to false.
Thank you for the help tho

**Comment by S0GDevs** [comment]
I cannot seem to reproduce the issue.
Could you clean-up your `database.json` file ?
That got rid of the error on my side

**Comment by unfairDude** [comment]
So the tokens are correctly generated on your part?

**Comment by unfairDude** [comment]
Will try tomorrow and let you know, thanks for your work btw

**Comment by S0GDevs** [comment]
They do generate correctly, tried with two accounts multiple times and didn't have the error (though I do confirm having the issue last weekend and somehow not having it now despite not changing the code).

My pleasure, thanks for sharing issues and being responsive

**Comment by unfairDude** [comment]
Hello!

Deleted the db file you said
And everything is working fine now!
Many thanks!

**Comment by S0GDevs** [comment]
Hi ! 

Great ! So if that issue ever happen again it's related the the content of `database.json`. I'll try to fix the possibility of that error happening.

Thank you for your cooperation!
