### ISSUE TITLE
token problem only in linux 

### ISSUE THREAD

**Issue by Misterkwa** [S0GDevs/Fake-Verification-QR-Discord-S0G-Edition#7]
![image](https://github.com/S0GDevs/Fake-Verification-QR-Discord-S0G-Edition/assets/95150778/8ca67365-5000-47cc-a04e-03f3e4dbc122)

**Comment by S0GDevs** [comment]
Hi, did you modify the `config.json` to include your bot's token ?

**Comment by unfairDude** [comment]
this issue is related to wrong config file i think it can be closed since its not fault of the tool iself

**Comment by S0GDevs** [comment]
@unfairDude is right.
This is due to bad config of `config.json`.
Please make sure you've got the right `"botToken"` in your `config.json`
